// <auto-generated />
using System;
using CalculoParaAcoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculoParaAcoesMVC.Migrations
{
    [DbContext(typeof(CalculosDbContext))]
    [Migration("20211022000648_Modelando")]
    partial class Modelando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CalculoParaAcoes.Models.DesvioPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abertura1Antes")
                        .IsRequired();

                    b.Property<DateTime>("DataCriado");

                    b.Property<string>("DesvPadrao")
                        .IsRequired();

                    b.Property<double>("Desvio1");

                    b.Property<double>("Desvio1n");

                    b.Property<double>("Desvio2");

                    b.Property<double>("Desvio2n");

                    b.Property<string>("FechamentoAtual")
                        .IsRequired();

                    b.Property<string>("NomeDaAcao")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DesvioPadrao");
                });

            modelBuilder.Entity("CalculoParaAcoes.Models.Zscore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AbaixoValorAtual");

                    b.Property<double>("AcimaValorAtual");

                    b.Property<DateTime>("DataCriado");

                    b.Property<int>("Dias");

                    b.Property<int>("DiasUteis");

                    b.Property<string>("Ewma")
                        .IsRequired();

                    b.Property<string>("NomeDaAcao")
                        .IsRequired();

                    b.Property<string>("PrecoAberturaMes")
                        .IsRequired();

                    b.Property<string>("PrecoAtual")
                        .IsRequired();

                    b.Property<double>("ValorZscore");

                    b.Property<string>("Variacao5Anos")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Zscore");
                });
#pragma warning restore 612, 618
        }
    }
}
